/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpc;

import httpc.entity.Header;
import httpc.entity.Request;
import httpc.model.HttpMethod;

import java.io.IOException;

import static httpc.model.HttpMethod.Get;

public class App {

  public static void main(String[] args) throws IOException {
    Client client =  new Client();


    Request request = new Request(HttpMethod.Get);
    client.send(request);

  }
}
