/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package httpc;

import httpc.entity.Request;

public class App {

  public static void main(String[] args) {
    Client client =  new Client();

    // parse cmd line args
    client.send(new Request());
  }
}
